<a href="https://colab.research.google.com/github/Arpit23creator/Form/blob/arpit/Numpypractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#np.array
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
#2D and 3D
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#dtype
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
#np.arange
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [6]:
#np.ones and np.zeroes
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#np.random
np.random.random((3, 4))

array([[0.70333863, 0.37890022, 0.65684639, 0.85896703],
       [0.65251178, 0.43040958, 0.62944699, 0.40314043],
       [0.09138303, 0.06653103, 0.99330223, 0.644685  ]])

In [9]:
#np.linspace
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes


In [11]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
#ndim
a3.ndim

3

In [13]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
#itemsize
a2.itemsize

8

In [15]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype


In [16]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [17]:
#scalar  operations

#arithmetic
a3/2

array([[[0. , 0.5],
        [1. , 1.5]],

       [[2. , 2.5],
        [3. , 3.5]]])

In [18]:
#relational
a2 > 3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [20]:
a1 = np.random.random((3, 3))
a2 = np.round(a1*100)
a2

array([[41., 18., 65.],
       [34., 94., 95.],
       [96., 57.,  6.]])

In [21]:
#mean/median/std/var
np.var(a1, axis=1)

array([0.03690968, 0.0805754 , 0.13499351])

In [22]:
#Trigonometric functions
np.sin(a1)

array([[0.39428811, 0.17799176, 0.60472978],
       [0.33597038, 0.80607567, 0.81447943],
       [0.81701792, 0.54254806, 0.05940394]])

In [23]:
#dot product
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [24]:
#log and exponents
np.exp(a1)

array([[1.49974197, 1.19595526, 1.91444265],
       [1.40865494, 2.55356599, 2.59044943],
       [2.60184336, 1.77440909, 1.06124095]])

In [25]:
#round/floor/ceil
np.ceil(np.random.random((2, 3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

Indexing and Slicing

In [26]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [27]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a2[1, 3]

np.int64(7)

In [29]:
a3[1, 0, 1]

np.int64(5)

In [30]:
a3[0, 0, 0]

np.int64(0)

In [31]:
a1[2:5:2]

array([2, 4])